directories:
  output: release
  buildResources: build
appId: com.mlimi.smart1
productName: MLIMI Smart
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
extraMetadata:
  main: dist-electron/main.js
asar: true
asarUnpack:
  - dist-electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
mac:
  target:
    - dmg
    - zip
linux:
  target:
    - AppImage
    - deb
electronVersion: 33.4.11
